#Expyriment 0.11.dev5 (Python 3.11.9), .xpe-file, coding: cp1252
#date: Fri Jan 17 2025 20:18:00
#sha1: 1cc390
#modules: 
#display: size=(800, 600), window_mode=False, opengl=2
#os: uname_result(system='Windows', node='Geoff3', release='10', version='10.0.22631', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
4809,Picture,loaded,C:\Users\ali_a\Desktop\Single_Word_Processing_Stage\Single_Word_Processing\Christophe_Stimulation\Images\Instructions\localizer_instructions.png
4884,Stimulus,presented,0
11699,Keyboard,received, ,wait_char
11703,stderr,received,'Traceback (most recent call last):'
11703,stderr,received,'  File "C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\Single_Word_Processing\\Christophe_Stimulation\\swp_localizer.py", line 51, in <module>'
11704,stderr,received,"    word = stimulus.split('_')[1]  # Extract the word from the file name"
11704,stderr,received,'           ^^^^^^^^^^^^^^'
11705,stderr,received,'  File "C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\.venv\\Lib\\site-packages\\pandas\\core\\generic.py", line 6299, in __getattr__'
11753,stderr,received,'    return object.__getattribute__(self, name)'
11754,stderr,received,'           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
11757,stderr,received,"AttributeError: 'Series' object has no attribute 'split'. Did you mean: 'plot'?"
